- Infrastructure:

    - UniFi Network:
        href: https://unifi.ui.com/
        description: Networking
        icon: unifi

    - Proxmox:
        href: {{HOMEPAGE_VAR_PROXMOX_HREF}}
        icon: proxmox
        ping: {{HOMEPAGE_VAR_PROXMOX_HREF}}
        widget:
          type: proxmox
          url: {{HOMEPAGE_VAR_PROXMOX_URL}}
          username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
          password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}

    - Pi-hole:
        href: {{HOMEPAGE_VAR_PIHOLE_HREF}}
        icon: pi-hole
        ping: {{HOMEPAGE_VAR_PIHOLE_HREF}}
        widget:
          type: pihole
          version: 6
          url: {{HOMEPAGE_VAR_PIHOLE_URL}}
          key: {{HOMEPAGE_VAR_PIHOLE_KEY}}

    - Nginx Proxy Manager:
        href: {{HOMEPAGE_VAR_NPM_HREF}}
        description: Reverse Proxy & TLS
        icon: nginx
        ping: {{HOMEPAGE_VAR_NPM_HREF}}

    - Home Assistant:
        href: {{HOMEPAGE_VAR_HA_HREF}}
        description: Smart Home Control
        ping: {{HOMEPAGE_VAR_HA_HREF}}
        icon: home-assistant

    - Portainer:
        href: {{HOMEPAGE_VAR_PORTAINER_HREF}}
        description: Docker Management
        ping: {{HOMEPAGE_VAR_PORTAINER_HREF}}
        icon: portainer
    
    - Grafana:
        href: {{HOMEPAGE_VAR_GRAFANA_HREF}}
        description: Data Visualization
        ping: {{HOMEPAGE_VAR_GRAFANA_HREF}}
        icon: grafana
        widget:
            type: grafana
            version: 2 # optional, default is 1
            url: {{HOMEPAGE_VAR_GRAFANA_API_URL}}
            username: {{HOMEPAGE_VAR_GRAFANA_USERNAME}}
            password: {{HOMEPAGE_VAR_GRAFANA_PASSWORD}}
    
    - InfluxDB:
        href: {{HOMEPAGE_VAR_INFLUXDB_HREF}}
        description: Time Series Data Storage
        ping: {{HOMEPAGE_VAR_INFLUXDB_HREF}}
        icon: influxdb